### ISSUE TITLE
Nomad-Ops sets node_pool to "default"

### ISSUE THREAD

**Issue by RafaelReder** [nomad-ops/nomad-ops#18]
Hello,

I experience the following behaviour: Everything runs smooth as long as I use the default node_pool. If i set a other node_pool in the job specification, Nomad-Ops changes it automatically back to default. Is this a known behaviour?

I am using Nomad 1.6.3 and Nomad Ops Main docker image.

Thank you

Best

**Comment by needsaholiday** [comment]
Sorry for the late reply. My notification settings were broken.

Try release v0.8.0. This should fix you issue.

Reopen if not fixed
