### ISSUE TITLE
Is NomadOps still under development?

### ISSUE THREAD

**Issue by datngtrue** [nomad-ops/nomad-ops#19]
Hi @needsaholiday @mzjulian,

I've just started with Nomad and find NomadOps helpful when it comes to enabling a simple CI/CD workflow for Nomad clusters.

At the moment, I'm working on adding the support for SSL certificate to connect to TLS-enabled clusters. I'll create a PR to the main upstream once I'm done.

The last update was in 2023. This makes me question that if NomadOps is still under development or should I continue use it. A status update would be helpful for me (and anyone considers using NomadOps for their stack later) to have a good plan for our cluster.

Thanks in advance,
Dat Nguyen

**Comment by needsaholiday** [comment]
Hey @datngtrue,
thanks for looking into this topic! Looking forward to it.

I have a couple of things on my mind that I will hopefully get to in the next month. It is been a busy year, that kept me from doing this :)

If you require something else just let me know or contribute yourself.

Thanks
